#"https://beta.todoist.com/API/v8/projects?token=$token"
app:
  host: https://beta.todoist.com
  root: /API
  version: /v8

user:
  token: 128e6b8cc03a28d04a7b418ff05a7e98feed1ffa
  #usename = bdt user  psw: Control123



